name: 'build fap'
author: 'Oleksii Kutuzov'
description: 'Github Action that builds your fap with ufbt'
branding:
  icon: 'align-left'  
  color: 'green'
inputs:
  fap-dir:
    description: 'Directory with your fap (you should checkout your repository to some folder'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout ufbt
      uses: actions/checkout@v3
      with:
        repository: flipperdevices/flipperzero-ufbt
        path: flipperzero-ufbt
        
    - name: Set path
      shell: bash
      run: echo "$GITHUB_WORKSPACE/flipperzero-ufbt" >> $GITHUB_PATH
      
    - name: Get directory.json
      shell: bash
      run: curl -o directory.json https://update.flipperzero.one/firmware/directory.json
      
    - name: Extract version from package.json
      uses: sergeysova/jq-action@v2
      id: version
      with:
        cmd: 'jq .channels[0].versions[0].version directory.json -r'
      
    - name: Cache toolchain
      id: cache-fbt
      uses: actions/cache@v3
      env:
        cache-name: cache-ftb-toolchain
      with:
        path: "$GITHUB_WORKSPACE/flipperzero-ufbt/.ufbt/"
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-${{ steps.version.outputs.value }}
          ${{ runner.os }}-${{ env.cache-name }}-
          ${{ runner.os }}-
          
    - if: ${{ steps.cache-fbt.outputs.cache-hit != 'true' }}
      name: Update ufbt
      shell: bash
      continue-on-error: false
      run: ufbt update
        
    - if: ${{ steps.cache-fbt.outputs.cache-hit != 'true' }}
      name: Save cache
      uses: actions/cache@v3
      env:
        cache-name: cache-ftb-toolchain
      with:
        path: "$GITHUB_WORKSPACE/flipperzero-ufbt/.ufbt/"
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ steps.version.outputs.value }}
      
    - name: Build fap
      shell: bash
      run: cd ${{ inputs.fap-dir }}; ufbt
