name: 'build fap'
author: 'Oleksii Kutuzov'
description: 'Github Action that builds your fap with ufbt'
branding:
  icon: 'align-left'  
  color: 'green'
inputs:
  fap-dir:
    description: 'Directory with your fap (you should checkout your repository to some folder'
    required: true
  channel:
    description: 'SDK channel to use'
    required: false
    default: 'dev'
runs:
  using: 'composite'
  steps:
    - name: Checkout ufbt
      uses: actions/checkout@v3
      with:
        repository: flipperdevices/flipperzero-ufbt
        path: flipperzero-ufbt
        
    - name: Set path
      shell: bash
      run: echo "$GITHUB_WORKSPACE/flipperzero-ufbt" >> $GITHUB_PATH
      
    - name: Get directory.json
      shell: bash
      run: curl -o directory.json https://update.flipperzero.one/firmware/directory.json
      
    - if: ${{ inputs.channel == 'dev' }}
      env:
        channel_n: 0
        
    - if: ${{ inputs.channel == 'rc' }}
      env:
        channel_n: 1
        
    - if: ${{ inputs.channel == 'release' }}
      env:
        channel_n: 2
      
    - name: Extract version from package.json
      uses: sergeysova/jq-action@v2
      id: version
      with:
        cmd: 'jq .channels[${{ env.channel_n }}].versions[0].version directory.json -r'
      
    - name: Cache toolchain
      id: cache-fbt
      uses: actions/cache@v3
      env:
        cache-name: cache-fbt-toolchain
      with:
        path: flipperzero-ufbt/.ufbt/
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ steps.version.outputs.value }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-${{ steps.version.outputs.value }}
      
    - name: Build fap
      shell: bash
      run: cd ${{ inputs.fap-dir }}; ufbt
